var fs = require('fs');
var utils = require("../../utils");
var expect = require('chai').expect;
const SubsectionElement = require('../../classes/subsec_element');

describe('Utility Functions', function () {

    var xmlJSObject;
    var xmlJSObjectTrimmed;
    var dirtyListHTML = fs.readFileSync(__dirname + '/input/dirty-list.html', 'utf8');

    var dirtySlidesHTML = fs.readFileSync(__dirname + '/input/dirty-slides.html', 'utf8');

    var dirtySlidesHTML2 = fs.readFileSync(__dirname + '/input/dirty-slides2.html', 'utf8');

    beforeEach(function() {
        // prodTicket = fs.readFileSync(__dirname + '/input/article.html', 'utf8');
        xmlJSObject = require('./input/xml-js-object');
        xmlJSObjectTrimmed = require('./input/xml-js-object-trimmed');
    });
    
    describe('#trimObjectText()', function () {
        it('should return trimmed "text" property of JavaScript Object', function () {
            var result = utils.trimObjectText(xmlJSObject)
            // console.log(xmlJSObject);
            expect(result).to.deep.equal(xmlJSObjectTrimmed);
        });
    });

    describe("#cleanHTML.unorderedList()", function () {
        it('should transform list generated by R2Net into proper <ul><li> list.', function () {
            var result = utils.cleanHTML.unorderedList(dirtyListHTML);
            fs.writeFileSync(__dirname + "/output/clean-list.html", result, function(err) {
                if(err) {
                    return console.log(err);
                }
            }); 
        });
    });

    describe("#cleanHTML.slides()", function () {
        it('should transform Slides HTML from from R2Net conversion into proper format.', function () {
            var result = utils.cleanHTML.slides(dirtySlidesHTML);
            fs.writeFileSync(__dirname + "/output/clean-slides.html", result, function(err) {
                if(err) {
                    return console.log(err);
                }
            }); 
        });
    });

    describe("#buildSlides()", function () {
        it('should transform Slides HTML from from R2Net conversion into JS Object.', function () {
            var subsectionElement = new SubsectionElement(true);
            var result = utils.buildSlides(dirtySlidesHTML2, subsectionElement, "901602");
            // fs.writeFileSync(__dirname + "/output/clean-slides.xml", result, function(err) {
            //     if(err) {
            //         return console.log(err);
            //     }
            // }); 
            utils.xmlOps.writeXMLFromObject(result.toObjectLiteral(), __dirname + "/output/clean-slides.xml");
        });
    });
});

